const data = [
  {
    id: 1,
    title: "Sims sims",
    price: 109.95,
    description:
      "Your perfect pack for everyday use and walks in the forest. Stash your laptop (up to 15 inches) in the padded sleeve, your everyday",
    category: "pc",
    genres: "simulation",
    age: "3+",
    image: "https://piterplay.com/image/catalog/kupit-far-cry-new-dawn-ps41.jpg",
    date: "2020-03-02",
    quantity: 1,
    count: 2,
    rating: {
      rate: 3.9,
    },
  },
  {
    id: 2,
    title: "Creation of trees",
    price: 22.3,
    description:
      "Slim-fitting style, three-button henley placket, light weight & soft fabric for breathable and comfortable wearing. And Solid stitched shirts with round neck made for durability and a great fit for casual fashion wear and diehard baseball fans. The Henley style round neckline includes a three-button placket.",
    category: "pc",
    genres: "simulation",
    age: "3+",
    image: "https://phonoteka.org/uploads/posts/2021-05/1621492016_25-phonoteka_org-p-fioletovii-fon-art-30.jpg",
    date: "2021-03-02",
    quantity: 1,
    count: 5,
    rating: {
      rate: 4.1,
    },
  },
  {
    id: 3,
    title: "Snake",
    price: 55.99,
    description:
      "designed by Michael Genesereth as part of the General Game Playing Project at Stanford University, California. GDL describes the state of a game as a series of facts, and the game mechanics as logical rules",
    category: "xbox",
    genres: "educational",
    age: "12+",
    image: "https://phonoteka.org/uploads/posts/2021-05/1621492016_25-phonoteka_org-p-fioletovii-fon-art-30.jpg",
    date: "2021-05-02",
    quantity: 1,
    count: 500,
    rating: {
      rate: 4.7,
    },
  },
  {
    id: 4,
    title: "New interesting unity game",
    price: 15.99,
    description:
      "The color could be slightly different between on the screen and in practice. / Please note that body builds vary by person, therefore, detailed size information should be reviewed below on the product description.",
    category: "playstation",
    genres: "shooter",
    age: "18+",
    image: "https://piterplay.com/image/catalog/kupit-far-cry-new-dawn-ps41.jpg",
    date: "2021-11-27",
    quantity: 1,
    count: 430,
    rating: {
      rate: 2.1,
    },
  },
  {
    id: 5,
    title: "We will create puzzle",
    price: 695,
    description:
      "From our Legends Collection, the Naga was inspired by the mythical water dragon that protects the ocean's pearl. Wear facing inward to be bestowed with love and abundance, or outward for protection.",
    category: "pc",
    genres: "action",
    age: "6+",
    image: "https://phonoteka.org/uploads/posts/2021-05/1621492016_25-phonoteka_org-p-fioletovii-fon-art-30.jpg",
    date: "2021-11-02",
    quantity: 1,
    count: 400,
    rating: {
      rate: 4.6,
    },
  },
  {
    id: 6,
    title: "Word of Tank ",
    price: 168,
    description:
      "Satisfaction Guaranteed. Return or exchange any order within 30 days.Designed and sold by Hafeez Center in the United States. Satisfaction Guaranteed. Return or exchange any order within 30 days.",
    category: "xbox",
    genres: "shooter",
    age: "18+",
    image: "https://torrentis.net/uploads/posts/2019-12/1482394485_sims-3-vse-dopolneniya-1.jpg",
    date: "2021-11-06",
    quantity: 1,
    count: 400,
    rating: {
      rate: 3.9,
    },
  },
  {
    id: 7,
    title: "Creation",
    price: 9.99,
    description:
      "designed by Michael Genesereth as part of the General Game Playing Project at Stanford University, California. GDL describes the state of a game as a series of facts, and the game mechanics as logical rules",
    category: "xbox",
    genres: "simulation",
    age: "3+",
    image: "https://phonoteka.org/uploads/posts/2021-05/1621492016_25-phonoteka_org-p-fioletovii-fon-art-30.jpg",
    quantity: 1,
    count: 400,
    rating: {
      rate: 3,
    },
  },
  {
    id: 8,
    title: "In the beggining",
    price: 10.99,
    description: "Rose Gold Plated Double Flared Tunnel Plug Earrings. Made of 316L Stainless Steel",
    category: "playstation",
    genres: "action",
    age: "12+",
    image: "https://piterplay.com/image/catalog/kupit-far-cry-new-dawn-ps41.jpg",
    date: "2021-07-02",
    quantity: 1,
    count: 100,
    rating: {
      rate: 1.9,
    },
  },
  {
    id: 9,
    title: "Sims 3",
    price: 64,
    description:
      "USB 3.0 and USB 2.0 Compatibility Fast data transfers Improve PC Performance High Capacity; Compatibility Formatted NTFS for Windows 10, Windows 8.1, Windows 7; Reformatting may be required for other operating systems; Compatibility may vary depending on user’s hardware configuration and operating system",
    category: "pc",
    genres: "simulation",
    age: "3+",
    image: "https://piterplay.com/image/catalog/kupit-far-cry-new-dawn-ps41.jpg",
    date: "2021-07-02",
    quantity: 1,
    count: 203,
    rating: {
      rate: 3.3,
    },
  },
  {
    id: 10,
    title: "New unity game 2.0.",
    price: 109,
    description:
      "Easy upgrade for faster boot up, shutdown, application load and response (As compared to 5400 RPM SATA 2.5” hard drive; Based on published specifications and internal benchmarking tests using PCMark vantage scores) Boosts burst write performance, making it ideal for typical PC workloads The perfect balance of performance and reliability Read/write speeds of up to 535MB/s/450MB/s (Based on internal testing; Performance may vary depending upon drive capacity, host device, OS and application.)",
    category: "xbox",
    genres: "shooter",
    age: "6+",
    image: "https://phonoteka.org/uploads/posts/2021-05/1621492016_25-phonoteka_org-p-fioletovii-fon-art-30.jpg",
    date: "2020-07-10",
    quantity: 1,
    count: 470,
    rating: {
      rate: 2.9,
    },
  },
  {
    id: 11,
    title: "Big hurmony",
    price: 109,
    description:
      "The advanced SLC Cache Technology allows performance boost and longer lifespan 7mm slim design suitable for Ultrabooks and Ultra-slim notebooks. Supports TRIM command, Garbage Collection technology, RAID, and ECC (Error Checking & Correction) to provide the optimized performance and enhanced reliability.",
    category: "pc",
    genres: "strategy",
    age: "3+",
    image: "https://torrentis.net/uploads/posts/2019-12/1482394485_sims-3-vse-dopolneniya-1.jpg",
    date: "2021-08-10",
    quantity: 1,
    count: 319,
    rating: {
      rate: 4.8,
    },
  },
  {
    id: 12,
    title: "Love love love",
    price: 114,
    description:
      "Expand your PS4 gaming experience, Play anywhere Fast and easy, setup Sleek design with high capacity, 3-year manufacturer's limited warranty",
    category: "playstation",
    genres: "simulation",
    age: "12+",
    image: "https://torrentis.net/uploads/posts/2019-12/1482394485_sims-3-vse-dopolneniya-1.jpg",
    date: "2021-10-02",
    quantity: 1,
    count: 400,
    rating: {
      rate: 4.8,
    },
  },
  {
    id: 13,
    title: "Word of interest",
    price: 599,
    description:
      "21. 5 inches Full HD (1920 x 1080) widescreen IPS display And Radeon free Sync technology. No compatibility for VESA Mount Refresh Rate: 75Hz - Using HDMI port Zero-frame design | ultra-thin | 4ms response time | IPS panel Aspect ratio - 16: 9. Color Supported - 16. 7 million colors. Brightness - 250 nit Tilt angle -5 degree to 15 degree. Horizontal viewing angle-178 degree. Vertical viewing angle-178 degree 75 hertz",
    category: "pc",
    genres: "action",
    age: "12+",
    image: "https://piterplay.com/image/catalog/kupit-far-cry-new-dawn-ps41.jpg",
    date: "2019-03-02",
    quantity: 1,
    count: 250,
    rating: {
      rate: 2.9,
    },
  },
  {
    id: 14,
    title: "Unity 10 ",
    price: 999.99,
    description:
      "designed by Michael Genesereth as part of the General Game Playing Project at Stanford University, California. GDL describes the state of a game as a series of facts, and the game mechanics as logical rules",
    category: "pc",
    genres: "action",
    age: "12+",
    image: "https://piterplay.com/image/catalog/kupit-far-cry-new-dawn-ps41.jpg",
    date: "2020-01-01",
    quantity: 1,
    count: 140,
    rating: {
      rate: 2.2,
    },
  },
  {
    id: 15,
    title: "Unity 2",
    price: 56.99,
    description:
      "designed by Michael Genesereth as part of the General Game Playing Project at Stanford University, California. GDL describes the state of a game as a series of facts, and the game mechanics as logical rulesIt is suitable for different season and help you adapt to different climates",
    category: "xbox",
    genres: "simulation",
    age: "3+",
    image: "https://piterplay.com/image/catalog/kupit-far-cry-new-dawn-ps41.jpg",
    date: "2021-05-02",
    quantity: 1,
    count: 235,
    rating: {
      rate: 2.6,
    },
  },
  {
    id: 16,
    title: "Unity 2",
    price: 56.99,
    description:
      "designed by Michael Genesereth as part of the General Game Playing Project at Stanford University, California. GDL describes the state of a game as a series of facts, and the game mechanics as logical rules",
    category: "xbox",
    genres: "fighting",
    age: "18+",
    image: "https://piterplay.com/image/catalog/kupit-far-cry-new-dawn-ps41.jpg",
    date: "2021-05-02",
    quantity: 1,
    count: 235,
    rating: {
      rate: 2.6,
    },
  },
  {
    id: 17,
    title: "Unity 2",
    price: 56.99,
    description:
      "designed by Michael Genesereth as part of the General Game Playing Project at Stanford University, California. GDL describes the state of a game as a series of facts, and the game mechanics as logical rules",
    category: "xbox",
    genres: "simulation",
    age: "6+",
    image: "https://piterplay.com/image/catalog/kupit-far-cry-new-dawn-ps41.jpg",
    date: "2021-05-02",
    quantity: 1,
    count: 235,
    rating: {
      rate: 2.6,
    },
  },
];
export default data;
