export const SIGN_IN_CONFIRMED_ACTION = "SIGN_IN_CONFIRMED_ACTION";
export const SIGN_IN_FAILED_ACTION = "SIGN_IN_FAILED_ACTION";
export const REGISTRATION_CONFIRMED_ACTION = "REGISTRATION_CONFIRMED_ACTION";
export const REGISTRATION_FAILED_ACTION = "REGISTRATION_FAILED_ACTION";
export const LOG_OUT_ACTION = "LOG_OUT_ACTION";
